name: Favorites manga and currently reading
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.anilist.manga.svg
  plugin_anilist_user: 'Fal3nx4ngel'
  token: NOT_NEEDED
  base: ""
  plugin_anilist: yes
  plugin_anilist_medias: anime,manga
  plugin_anilist_sections: favorites,watching,reading,characters
  plugin_anilist_limit: 1
